USE master;
GO

ALTER DATABASE SistemaAlertaTemprana SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO

DROP DATABASE SistemaAlertaTemprana;
GO

CREATE DATABASE SistemaAlertaTemprana;
GO

USE SistemaAlertaTemprana;
GO

CREATE TABLE Estudiantes (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    DNI VARCHAR(20) NOT NULL UNIQUE,
    Nombre VARCHAR(100) NOT NULL,
    Apellido VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NULL
);
GO

CREATE TABLE Clases (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Fecha DATE NOT NULL
);
GO

CREATE TABLE Asistencias (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    EstudianteId INT NOT NULL,
    ClaseId INT NOT NULL,
    Presente BIT NOT NULL,
    CONSTRAINT FK_Asistencias_Estudiantes FOREIGN KEY (EstudianteId) REFERENCES Estudiantes(Id) ON DELETE CASCADE,
    CONSTRAINT FK_Asistencias_Clases FOREIGN KEY (ClaseId) REFERENCES Clases(Id) ON DELETE CASCADE
);
GO